config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :neighborhoods

      resources :bookmarks

      resources :venues

      resources :favorited_dishes

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "users#index"
  resources :neighborhoods
  resources :bookmarks
  resources :venues
  resources :favorited_dishes
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/venue.rb
class Venue < ApplicationRecord
  # Direct associations

  belongs_to :neighborhood

  has_many   :bookmarks,
             foreign_key: "venues_id",
             dependent: :destroy

  # Indirect associations

  has_many   :users,
             through: :bookmarks,
             source: :user

  # Validations

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/venues_controller.rb
class Api::V1::VenuesController < Api::V1::GraphitiController
  def index
    venues = VenueResource.all(params)
    respond_with(venues)
  end

  def show
    venue = VenueResource.find(params)
    respond_with(venue)
  end

  def create
    venue = VenueResource.build(params)

    if venue.save
      render jsonapi: venue, status: :created
    else
      render jsonapi_errors: venue
    end
  end

  def update
    venue = VenueResource.find(params)

    if venue.update_attributes
      render jsonapi: venue
    else
      render jsonapi_errors: venue
    end
  end

  def destroy
    venue = VenueResource.find(params)

    if venue.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: venue
    end
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: %i[show edit update destroy]

  def index
    @q = Venue.ransack(params[:q])
    @venues = @q.result(distinct: true).includes(:bookmarks, :neighborhood,
                                                 :users).page(params[:page]).per(10)
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @venue = Venue.new
  end

  def edit; end

  def create
    @venue = Venue.new(venue_params)

    if @venue.save
      message = "Venue was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @venue, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @venue.update(venue_params)
      redirect_to @venue, notice: "Venue was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @venue.destroy
    message = "Venue was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to venues_url, notice: message
    end
  end

  private

  def set_venue
    @venue = Venue.find(params[:id])
  end

  def venue_params
    params.require(:venue).permit(:name, :address, :neighborhood_id)
  end
end

app/views/venues/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Venue #<%= venue.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= venue.name %></dd>

      <dt>Address</dt>
      <dd><%= venue.address %></dd>

      <dt>Neighborhood</dt>
      <dd>
        <% if @venue.neighborhood.present? %>
          <%= link_to venue.neighborhood, venue.neighborhood %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back venue, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_venue_url(venue), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to venue, method: :delete, data: { confirm: "Do you really want to delete this venue?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(venue.updated_at) %> ago
  </div>
</div>

app/views/venues/_form.html.erb
<% was_validated = venue.errors.any? %>

<%= form_with(model: venue, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = venue.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_area :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% venue.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% address_class = "form-control" %>
    <% address_was_invalid = venue.errors.include?(:address) %>

    <% if was_validated %>
      <% if address_was_invalid %>
        <% address_class << " is-invalid" %>
      <% else %>
        <% address_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :address %>
    <%= f.text_field :address, class: address_class, placeholder: "Enter address" %>
    <% if address_was_invalid %>
      <% venue.errors.full_messages_for(:address).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% neighborhood_class = "form-control" %>
    <% neighborhood_was_invalid = venue.errors.include?(:neighborhood) %>

    <% if was_validated %>
      <% if neighborhood_was_invalid %>
        <% neighborhood_class << " is-invalid" %>
      <% else %>
        <% neighborhood_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :neighborhood_id %>
    <%= f.collection_select :neighborhood_id, Neighborhood.all, :id, :to_s, {}, class: "form-control" %>
    <% if neighborhood_was_invalid %>
      <% venue.errors.full_messages_for(:neighborhood).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/venues/_list_item.html.erb
<%= link_to venue, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= venue %>
    <small class="text-muted">
      <%= time_ago_in_words(venue.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/venues/_venue_bookmarks.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Bookmarks

    <a data-toggle="collapse" href="#venue_bookmarks_new_form">
      Add bookmark
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @venue.bookmarks.each do |bookmark| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to bookmark, bookmark %>

        <%= link_to bookmark, method: :delete, data: { confirm: "Do you really want to delete this bookmark" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="venue_bookmarks_new_form">
        <%= render partial: "venues/venue_bookmarks_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/venues/_venue_bookmarks_new_form.html.erb
<%= form_with(model: @bookmark, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :user_id %>

    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :dish_id %>

    <%= f.collection_select :dish_id, FavoritedDish.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :venues_id, value: @venue.id %>

  <%= f.submit "Create bookmark", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/venues/_venue_users.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Users
  </div>

  <ul class="list-group list-group-flush">
    <% @venue.users.each do |user| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/users/<%= user.id %>">
          <%= user %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/venues/_venues_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "venues_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :address_cont, "Address contains" %>
    <%= f.text_field :address_cont, :class => "form-control", :placeholder => "Address contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :neighborhood_name_cont, "Neighborhood name contains" %>
    <%= f.text_field :neighborhood_name_cont, :class => "form-control", :placeholder => "Neighborhood name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :users_email_cont, "Users email contains" %>
    <%= f.text_field :users_email_cont, :class => "form-control", :placeholder => "Users email contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/venues" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#venues_filters">
  Show filters
</a>

app/views/venues/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Venue #<%= @venue.id %>
      </h2>

      <div class="card-body">
        <%= render "form", venue: @venue %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/venues/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Venues

      <%= link_to new_venue_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "venues/venues_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Venues

        <%= link_to new_venue_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @venues, partial: "list_item", as: :venue %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @venues, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/venues/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Venue
      </h2>

      <div class="card-body">
        <%= render "form", venue: @venue %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/venues/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @venue, partial: "card", as: :venue %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "venues/venue_bookmarks" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "venues/venue_users" %>
  </div>
</div>