config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :neighborhoods

      resources :bookmarks

      resources :venues

      resources :favorited_dishes

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "users#index"
  resources :neighborhoods
  resources :bookmarks
  resources :venues
  resources :favorited_dishes
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favorited_dish.rb
class FavoritedDish < ApplicationRecord
  # Direct associations

  has_many   :bookmarks,
             foreign_key: "dish_id",
             dependent: :destroy

  # Indirect associations

  has_many   :users,
             through: :bookmarks,
             source: :user

  # Validations

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/favorited_dishes_controller.rb
class Api::V1::FavoritedDishesController < Api::V1::GraphitiController
  def index
    favorited_dishes = FavoritedDishResource.all(params)
    respond_with(favorited_dishes)
  end

  def show
    favorited_dish = FavoritedDishResource.find(params)
    respond_with(favorited_dish)
  end

  def create
    favorited_dish = FavoritedDishResource.build(params)

    if favorited_dish.save
      render jsonapi: favorited_dish, status: :created
    else
      render jsonapi_errors: favorited_dish
    end
  end

  def update
    favorited_dish = FavoritedDishResource.find(params)

    if favorited_dish.update_attributes
      render jsonapi: favorited_dish
    else
      render jsonapi_errors: favorited_dish
    end
  end

  def destroy
    favorited_dish = FavoritedDishResource.find(params)

    if favorited_dish.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: favorited_dish
    end
  end
end

app/controllers/favorited_dishes_controller.rb
class FavoritedDishesController < ApplicationController
  before_action :set_favorited_dish, only: %i[show edit update destroy]

  def index
    @q = FavoritedDish.ransack(params[:q])
    @favorited_dishes = @q.result(distinct: true).includes(:bookmarks,
                                                           :users).page(params[:page]).per(10)
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @favorited_dish = FavoritedDish.new
  end

  def edit; end

  def create
    @favorited_dish = FavoritedDish.new(favorited_dish_params)

    if @favorited_dish.save
      redirect_to @favorited_dish,
                  notice: "Favorited dish was successfully created."
    else
      render :new
    end
  end

  def update
    if @favorited_dish.update(favorited_dish_params)
      redirect_to @favorited_dish,
                  notice: "Favorited dish was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @favorited_dish.destroy
    redirect_to favorited_dishes_url,
                notice: "Favorited dish was successfully destroyed."
  end

  private

  def set_favorited_dish
    @favorited_dish = FavoritedDish.find(params[:id])
  end

  def favorited_dish_params
    params.require(:favorited_dish).permit(:name, :cuisine, :venues_id,
                                           :user_id)
  end
end

app/views/favorited_dishes/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Favorited Dish #<%= favorited_dish.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= favorited_dish.name %></dd>

      <dt>Cuisine</dt>
      <dd><%= favorited_dish.cuisine %></dd>

      <dt>Venues</dt>
      <dd><%= favorited_dish.venues_id %></dd>

      <dt>User</dt>
      <dd><%= favorited_dish.user_id %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back favorited_dish, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_favorited_dish_url(favorited_dish), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to favorited_dish, method: :delete, data: { confirm: "Do you really want to delete this favorited_dish?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(favorited_dish.updated_at) %> ago
  </div>
</div>

app/views/favorited_dishes/_favorited_dish_bookmarks.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Bookmarks

    <a data-toggle="collapse" href="#favorited_dish_bookmarks_new_form">
      Add bookmark
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @favorited_dish.bookmarks.each do |bookmark| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to bookmark, bookmark %>

        <%= link_to bookmark, method: :delete, data: { confirm: "Do you really want to delete this bookmark" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="favorited_dish_bookmarks_new_form">
        <%= render partial: "favorited_dishes/favorited_dish_bookmarks_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/favorited_dishes/_favorited_dish_bookmarks_new_form.html.erb
<%= form_with(model: @bookmark, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :user_id %>

    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :dish_id, value: @favorited_dish.id %>

  <div class="form-group">
    <%= f.label :venues_id %>

    <%= f.collection_select :venues_id, Venue.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.submit "Create bookmark", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/favorited_dishes/_favorited_dish_users.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Users
  </div>

  <ul class="list-group list-group-flush">
    <% @favorited_dish.users.each do |user| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/users/<%= user.id %>">
          <%= user %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/favorited_dishes/_favorited_dishes_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "favorited_dishes_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :user_id, "User" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :user_id_gteq, :class => "form-control", :placeholder => "User greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :user_id_lteq, :class => "form-control", :placeholder => "User less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :venues_id, "Venues" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :venues_id_gteq, :class => "form-control", :placeholder => "Venues greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :venues_id_lteq, :class => "form-control", :placeholder => "Venues less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :cuisine_cont, "Cuisine contains" %>
    <%= f.text_field :cuisine_cont, :class => "form-control", :placeholder => "Cuisine contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :users_email_cont, "Users email contains" %>
    <%= f.text_field :users_email_cont, :class => "form-control", :placeholder => "Users email contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/favorited_dishes" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#favorited_dishes_filters">
  Show filters
</a>

app/views/favorited_dishes/_form.html.erb
<% was_validated = favorited_dish.errors.any? %>

<%= form_with(model: favorited_dish, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = favorited_dish.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_area :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% favorited_dish.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% cuisine_class = "form-control" %>
    <% cuisine_was_invalid = favorited_dish.errors.include?(:cuisine) %>

    <% if was_validated %>
      <% if cuisine_was_invalid %>
        <% cuisine_class << " is-invalid" %>
      <% else %>
        <% cuisine_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :cuisine %>
    <%= f.text_area :cuisine, class: cuisine_class, placeholder: "Enter cuisine" %>
    <% if cuisine_was_invalid %>
      <% favorited_dish.errors.full_messages_for(:cuisine).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% venue_class = "form-control" %>
    <% venue_was_invalid = favorited_dish.errors.include?(:venue) %>

    <% if was_validated %>
      <% if venue_was_invalid %>
        <% venue_class << " is-invalid" %>
      <% else %>
        <% venue_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :venues_id %>
    <%= f.number_field :venues_id, class: venue_class, placeholder: "Enter venue" %>
    <% if venue_was_invalid %>
      <% favorited_dish.errors.full_messages_for(:venue).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% user_class = "form-control" %>
    <% user_was_invalid = favorited_dish.errors.include?(:user) %>

    <% if was_validated %>
      <% if user_was_invalid %>
        <% user_class << " is-invalid" %>
      <% else %>
        <% user_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :user_id %>
    <%= f.number_field :user_id, class: user_class, placeholder: "Enter user" %>
    <% if user_was_invalid %>
      <% favorited_dish.errors.full_messages_for(:user).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/favorited_dishes/_list_item.html.erb
<%= link_to favorited_dish, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= favorited_dish %>
    <small class="text-muted">
      <%= time_ago_in_words(favorited_dish.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/favorited_dishes/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Favorited Dish #<%= @favorited_dish.id %>
      </h2>

      <div class="card-body">
        <%= render "form", favorited_dish: @favorited_dish %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorited_dishes/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Favorited Dishes

      <%= link_to new_favorited_dish_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "favorited_dishes/favorited_dishes_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Favorited Dishes

        <%= link_to new_favorited_dish_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @favorited_dishes, partial: "list_item", as: :favorited_dish %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @favorited_dishes, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/favorited_dishes/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Favorited Dish
      </h2>

      <div class="card-body">
        <%= render "form", favorited_dish: @favorited_dish %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorited_dishes/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @favorited_dish, partial: "card", as: :favorited_dish %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "favorited_dishes/favorited_dish_bookmarks" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "favorited_dishes/favorited_dish_users" %>
  </div>
</div>